export default function getSubjectsArray(): string[] {
  return [
    'ACST',
    'APE',
    'APH',
    'API',
    'APM',
    'APS',
    'Arte',
    'Biologia',
    'CLP',
    'E. Digital',
    'E. Industrial',
    'E. de Potência',
    'Ed. Física',
    'Eletricidade I',
    'Eletricidade II',
    'Eletrônica II',
    'FP',
    'Filosofia',
    'Física',
    'Geografia',
    'História',
    'IMC',
    'L. Inglesa',
    'L. Portuguesa',
    'LPII',
    'LPIII',
    'LTP',
    'Matemática',
    'Micro',
    'ONST',
    'PDM',
    'PPBD',
    'PW',
    'Química',
    'Sociologia',
    'Tec. Industriais',
    'UX',
  ];
}
