export default function getSubjectsArray(): string[] {
  return [
    'ACST',
    'APE',
    'API',
    'APM',
    'APH',
    'APS',
    'Arte',
    'PPBD',
    'Biologia',
    'CLP',
    'Ed. Física',
    'Eletricidade I',
    'Eletricidade II',
    'Eletrônica II',
    'E. Digital',
    'E. Industrial',
    'E. de Potência',
    'Filosofia',
    'Física',
    'FP',
    'Geografia',
    'História',
    'IMC',
    'L. Inglesa',
    'L. Portuguesa',
    'LTP',
    'LPII',
    'LPIII',
    'PW',
    'Matemática',
    'PDM',
    'Micro',
    'ONST',
    'Química',
    'Sociologia',
    'Tec. Industriais',
    'UX',
  ];
}
